# Generated by Django 2.2.4 on 2019-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191201_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('NO', 'SELECT CATEGORY'), ('MP', 'Mens Products'), ('WP', 'Womens Products'), ('KD', 'Kids Products'), ('SP', 'Stationery Products'), ('HKP', 'Home Kitchen Products'), ('SFP', 'Sports Fitness Products'), ('EP', 'Electronics Products')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], max_length=1),
        ),
    ]
